title: 'Youth Dance Weekend'
slogan: 'Youth Dance Weekend'
description: 'YDW is a youth-focused traditional dance and music gathering featuring lots of contra, English, and couples dancing, as well as singing, jamming, and opportunities to get to know cool people from near and far.'
credits: '<p>Created with &hearts; by <a href="https://richard.science/">Richard</a> with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a>.</p>'

author: rbarnes

navigation:
  - title: Home
    url: "/"
    side: left
  - title: About
    url: "/about/"
    side: left
  - title: Policies
    url: "/policies/"
    side: left
  - title: FAQ
    url: "/faq/"
    side: left
  - title: Donate
    url: "/donate/"
    side: left
  - title: Recipes
    url: "/recipes/"
    side: left
  - title: Contact
    url: "/contact/"
    side: right

url: 'https://youthdanceweekend.org'
baseurl: '/'

urlimg: 'https://youthdanceweekend.org/images/'

# Logo size is 600x80 pixels
logo: "logo.png"


markdown           : kramdown
permalink          : /:title/
highlight          : rouge
include            : ['.htaccess']
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - vendor

language: 'en'

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      show_meta: false
      comments: false
      author: rbarnes

favicon-32x32                        : 'favicon-32x32.png'
apple-touch-icon-180x180-precomposed : 'apple-touch-icon.png'
apple-touch-icon-precomposed         : 'apple-touch-icon.png'

og_locale                            : 'en_EN'
og_type                              : 'website'

sass:
    sass_dir : _sass
    style    : :compressed
