#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml
#

url:    'http://localhost:4001'
baseurl: ''
urlimg:  'http://localhost:4001/images/'

sass:
  style: :expanded
  line_numbers: true
