description: 'YDW is a youth-focused traditional dance and music gathering featuring lots of contra, English, and couples dancing, as well as singing, jamming, and opportunities to get to know cool people from near and far.'
data_dir: .
destination: _generated_site
layouts_dir: framework/layouts
includes_dir: framework/includes

url: 'https://youthdanceweekend.org'
baseurl: '/'

urlimg: 'https://youthdanceweekend.org/images/'

# Logo size is 600x80 pixels
logo: "logo.png"


markdown           : kramdown
permalink          : /:title/
highlight          : rouge
include            : ['.htaccess']
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - vendor

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      show_meta: false
      comments: false

sass:
    sass_dir : framework/sass
    style    : :compressed
